image: node:20

name: React CI

stages:
  - name: install
    commands:
      - npm ci

  - name: lint
    commands:
      - npm run lint

  - name: test
    commands:
      - npm test -- --watchAll=false

  - name: build
    commands:
      - npm run build

artifacts:
  - build/**
  - coverage/**