jobs:
  build:
    image: node:20
    steps:
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test -- --watchAll=false
      - name: Build
        run: npm run build
    artifacts:
      - build/**
      - coverage/**