jobs:
  - name: install
    run: npm install
    image: node:20

  - name: build
    run: |
      npm install
      npm run build
    image: node:20
    artifacts:
      - build/**
      - coverage/**